### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [It-is-Alex/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by It-is-Alex** [comment]
Thank for the heads up, I think I've fixed what you were talking about.

**Comment by kenmazaika** [comment]
Close!  Right now you  have this:

```
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
```

But you're missing the closing `>` for the HTML element.  It should look like this:

```
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
```

**Comment by It-is-Alex** [comment]
Fixed.

**Comment by kenmazaika** [comment]
Thumbs up! :+1: :)
